version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  flask_server:
    build: .
    container_name: flask_server
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      FLASK_PORT: ${FLASK_PORT}
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
